### ISSUE TITLE
只支持vector格式的图吗

### ISSUE THREAD

**Issue by lgq895767507** [cpacm/FloatingMusicMenu#2]
FloatingActionButton在FloatingMusicMenu中，更换图片背景，貌似FloatingActionButton放png的不显示？只支持vector格式的吗？？？

**Comment by cpacm** [comment]
并不会，FloatingActionButton 是使用官方默认的控件。

**Comment by lgq895767507** [comment]
我知道FloatingActionButton是官方控件，可是父控件是FloatingMusicMenu的时候，调试png图片作为背景，图片不显示，在你的demo中，你引入的是vector类型的背景图，你有调试过png的图吗？？求帮忙确认下。

**Comment by cpacm** [comment]
FloatingActionButton可以使用setImageResource()设置图片。
你说的设置png图片作为背景是调的哪个方法？
