### ISSUE TITLE
图片无法占满控件

### ISSUE THREAD

**Issue by windflowersnowandmoon** [cpacm/FloatingMusicMenu#5]
minSdkVersion 19
targetSdkVersion 28

我是使用的这版本

**Comment by Soap613** [comment]
我也是这个问题，不知道怎么解决呢，貌似28版本这个组件重写了

**Comment by windflowersnowandmoon** [comment]
> 我也是这个问题，不知道怎么解决呢，貌似28版本这个组件重写了

这个问题我已经解决了， 里面的反射问题。

**Comment by Soap613** [comment]
应该怎么处理呢？求处理方式

**Comment by MRYangY** [comment]
> > 我也是这个问题，不知道怎么解决呢，貌似28版本这个组件重写了
> 
> 这个问题我已经解决了， 里面的反射问题。

请问是如何解决的？？

**Comment by windflowersnowandmoon** [comment]
> 应该怎么处理呢？求处理方式

FloatingMusicButton类里面，setMaxImageSize()方法，修改下mMaxImageSize 改成maxImageSize，后来额度版本里面的变量名称变了。其实自己写也简单，一个imageview，加一个转圈圈的动画，效果一样，和这个差不多，就是没有进度而已。

**Comment by windflowersnowandmoon** [comment]
> > > 我也是这个问题，不知道怎么解决呢，貌似28版本这个组件重写了
> > 
> > 
> > 这个问题我已经解决了， 里面的反射问题。
> 
> 请问是如何解决的？？

FloatingMusicButton类里面，setMaxImageSize()方法，修改下mMaxImageSize 改成maxImageSize，后来额度版本里面的变量名称变了。其实自己写也简单，一个imageview，加一个转圈圈的动画，效果一样，和这个差不多，就是没有进度而已。

**Comment by MRYangY** [comment]
> > 应该怎么处理呢？求处理方式
> 
> FloatingMusicButton类里面，setMaxImageSize()方法，修改下mMaxImageSize 改成maxImageSize，后来额度版本里面的变量名称变了。其实自己写也简单，一个imageview，加一个转圈圈的动画，效果一样，和这个差不多，就是没有进度而已。

我改了，还是不行，图片跑到了左上角，还有其他的设置吗？

**Comment by MRYangY** [comment]
> > 应该怎么处理呢？求处理方式
> 
> FloatingMusicButton类里面，setMaxImageSize()方法，修改下mMaxImageSize 改成maxImageSize，后来额度版本里面的变量名称变了。其实自己写也简单，一个imageview，加一个转圈圈的动画，效果一样，和这个差不多，就是没有进度而已。

            Class clazz = getClass().getSuperclass();
            Method sizeMethod = clazz.getDeclaredMethod("getSizeDimension", null);
            sizeMethod.setAccessible(true);
            int size = (Integer) sizeMethod.invoke(this,null);
            Field field = clazz.getDeclaredField("maxImageSize");
            field.setAccessible(true);
            field.set(this, size);

**Comment by Soap613** [comment]
谢谢

**Comment by cpacm** [comment]
3109d9a45d14a4c5fcac2c25f222b3cbc17bbe92 
merge androidx
